
import { GoogleGenAI, Type } from "@google/genai";
import { AnalysisResult } from "../types";

const API_KEY = process.env.API_KEY;

export class GeminiService {
  private ai: any;

  constructor() {
    this.ai = new GoogleGenAI({ apiKey: API_KEY! });
  }

  /**
   * Analyzes the user's uploaded photo using gemini-3-pro-preview
   */
  async analyzeUserPhoto(base64Image: string): Promise<AnalysisResult> {
    const prompt = `
      Analyze this portrait. Provide a structured description of the person's facial features to help an AI image generator maintain likeness.
      Identify:
      1. Dominant facial features (nose shape, eye color, jawline).
      2. Hair color and style.
      3. Likely gender expression (for wardrobe matching).
      4. General facial structure.
      Return the result in JSON format.
    `;

    const response = await this.ai.models.generateContent({
      model: 'gemini-3-pro-preview',
      contents: {
        parts: [
          { inlineData: { mimeType: 'image/jpeg', data: base64Image } },
          { text: prompt }
        ]
      },
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            features: { type: Type.STRING },
            style: { type: Type.STRING },
            genderEstimate: { type: Type.STRING },
            hairDescription: { type: Type.STRING },
          },
          required: ["features", "style", "genderEstimate", "hairDescription"]
        }
      }
    });

    return JSON.parse(response.text);
  }

  /**
   * Transforms the photo into a historical scene using gemini-2.5-flash-image
   */
  async transformImage(base64Image: string, eraPrompt: string, analysis: AnalysisResult): Promise<string> {
    const fullPrompt = `
      Maintain the face from the original image. 
      Person has: ${analysis.features}, ${analysis.hairDescription}.
      Transform the person and the entire scene into: ${eraPrompt}.
      The person should be the central figure. Maintain consistent facial characteristics.
    `;

    const response = await this.ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { inlineData: { mimeType: 'image/jpeg', data: base64Image } },
          { text: fullPrompt }
        ]
      }
    });

    let imageUrl = '';
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        imageUrl = `data:image/png;base64,${part.inlineData.data}`;
        break;
      }
    }

    if (!imageUrl) throw new Error("No image generated by Gemini");
    return imageUrl;
  }

  /**
   * Refines the generated image based on user text prompts
   */
  async refineImage(base64Image: string, editPrompt: string): Promise<string> {
    const response = await this.ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { inlineData: { mimeType: 'image/png', data: base64Image.split(',')[1] } },
          { text: `Apply the following change: ${editPrompt}. Maintain the composition and the person's face but modify according to the instruction.` }
        ]
      }
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    
    throw new Error("No edited image generated");
  }
}

export const geminiService = new GeminiService();
